name: scisco_service
version: 3.0.0+3
publish_to: none
description: A new Flutter application.
environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    cupertino_icons: ^1.0.2
    permission_handler: ^10.1.0
    toast: ^0.3.0
    fluttertoast: ^8.0.9
    dio: ^4.0.0
    location: ^4.4.0
    google_maps_flutter: ^2.1.4
    sliding_up_panel: ^2.0.0+1
    dotted_border: any
    image_picker: ^0.8.5
    shared_preferences: ^2.0.5
    ars_progress_dialog: ^0.1.2
    fancy_bottom_navigation: ^0.3.3
    path_provider: any
    path: any
    camera: ^0.9.4+20
    flutter_image_compress: ^1.0.0
    overlay_support: ^1.0.0
    universal_platform: ^1.0.0+1
    multi_image_picker: ^4.7.14
    get: 4.6.1
    flutter_polyline_points: 1.0.0
    intl: 0.17.0
    timelines: 0.1.0
    url_launcher: 6.1.0
    shimmer_animation: 2.1.0+1
    cached_network_image: ^3.2.2
    webview_flutter: ^1.0.7
    flutter_inappwebview: ^5.4.4+3
    #get_storage: ^2.0.3

    flutter:
        sdk: flutter
    firebase_crashlytics: ^2.8.1

dev_dependencies:
    flutter_launcher_icons: "^0.9.2"
    flutter_test:
        sdk: flutter

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/logo.jpeg"

flutter:
    fonts:
        - family: PriximaNova
          fonts:
          - asset: assets/fonts/proxima_nova.otf
    assets:
        - assets/images/
        - assets/icons/
        - assets/images/scisco.png
        - assets/images/dashboard/
        - assets/images/qrLoading.gif
        - assets/images/punch_in.gif
        - assets/images/new_installation_done.jpeg
        - assets/images/new_installation_pending.jpg
        - assets/images/new_punch_in.jpg
        - assets/images/new_service_done.jpg
        - assets/images/new_service_pending.jpg
    uses-material-design: true
